name: NPC
author: jojoe77777
version: 1.4.0
description: NPC plugin for PocketMine-MP
main: slapper\Main
api: [3.0.0-ALPHA12, 4.0.0]
website: https://github.com/jojoe77777/Slapper

commands:
  npc:
    description: Create a Slapper NPC, or edit an existing one!
    usage: "/slapper [args]..."
    permission: npc.command
  sudo:
    description: Execute a command as someone else!
    usage: "/rca <player> <command>"
    permission: npc.sudo
  nothing:
    description: Do nothing!
    usage: "/nothing"
    permission: npc.nothing

permissions:
  npc:
    description: Allow using all Slapper commands
    default: op
    children:
      npc.command:
        description: Allow using /npc
        default: op
      npc.create:
        description: Allow using command /npc create
        default: op
      npc.edit:
        description: Allow editing Slapper entity data with /npc edit
        default: op
      npc.nothing:
        description: Allow doing nothing
        default: op
      npc.sudo:
        description: Allow running commands as other players
        default: op
      npc.remove:
        description: Allow removing npc entities with /npc remove [id]
        default: op
      npc.id:
        description: Allow viewing entity ID
        default: op
      npc.help:
        description: Allow viewing npc help page
        default: op
